spring.application.name: tippabgabe


server.port: 7081

# H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2
h2.tcp.enabled: true
h2.tcp.port: 7091

# Datasource
spring.datasource:
  url: jdbc:h2:file:~/tippabgabe
  username: sa
  password:

# Kafka
spring.kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
  consumer:
    group-id: ${spring.application.name}
    auto-offset-reset: latest
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Logging
logging.level.root: INFO

# Clients
clients.spielplan.url: http://localhost:7080
